version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    environment:
      - MONGO_INITDB_DATABASE=system-info
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1SatnamW    
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null  
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  edge-gateway:
    image: sinny777/edge-gateway:latest
    # build:
    #   context: ./services/edge-gateway
    container_name: 'edge-gateway'
    restart: on-failure
    command:
      - '-b'
      - '0.0.0.0'    
    environment:
      - DB_CONNECTOR=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME='admin'
      - DB_PASSWORD='1SatnamW'
      - DB_NAME=admin
    ports:
      - '9000:8080'
    links:
      - mongodb
    depends_on:
      - mongodb
  
